name: Daily Menu Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-menu:
    runs-on: ubuntu-latest
    env:
      MENU_API: ${{ secrets.MENU_API }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build browser bundle
        run: npm run build:menu

      - name: Generate menu data from dist build
        run: node dist/menu.js --generate --out data/menu-data.json

      - name: Upload menu assets
        uses: actions/upload-artifact@v4
        with:
          name: menu-assets
          path: |
            data/menu-data.json
            dist/menu.js

      - name: Commit and push updated menu data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/menu-data.json
          if git diff --cached --quiet; then
            echo "No menu data changes to commit."
          else
            git commit -m "chore: update menu data"
            git push
          fi
